services:
  vault:
    image: hashicorp/vault:1.15
    container_name: gc-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_ADDR: "http://0.0.0.0:8200"
    command: server -dev -dev-root-token-id=${VAULT_TOKEN}
    cap_add:
      - IPC_LOCK
    networks:
      - goldencity-network

  redis-master:
    image: redis:7.2.4-alpine
    container_name: gc-redis-master
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --appendonly yes
    networks:
      - goldencity-network
    volumes:
      - redis-master-data:/data

  redis-replica:
    image: redis:7.2.4-alpine
    container_name: gc-redis-replica
    ports:
      - "6380:6380"
    command: >
      redis-server
      --port 6380
      --replicaof redis-master 6379
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --appendonly yes
    depends_on:
      - redis-master
    networks:
      - goldencity-network
    volumes:
      - redis-replica-data:/data

  sentinel1:
    image: redis:7.2.4-alpine
    container_name: gc-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./redis-config/sentinel_26379.conf:/etc/redis/sentinel.conf
      - sentinel1-data:/data
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - goldencity-network

  sentinel2:
    image: redis:7.2.4-alpine
    container_name: gc-sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - ./redis-config/sentinel_26380.conf:/etc/redis/sentinel.conf
      - sentinel2-data:/data
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - goldencity-network

  sentinel3:
    image: redis:7.2.4-alpine
    container_name: gc-sentinel-3
    ports:
      - "26381:26379"
    volumes:
      - ./redis-config/sentinel_26381.conf:/etc/redis/sentinel.conf
      - sentinel3-data:/data
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - goldencity-network

networks:
  goldencity-network:
    driver: bridge

volumes:
  redis-master-data:
  redis-replica-data:
  sentinel1-data:
  sentinel2-data:
  sentinel3-data: